### ISSUE TITLE
Log reconstruction samples

### ISSUE THREAD

**Issue by borisdayma** [patil-suraj/vit-vqgan#7]
We should log some samples (64?) during evaluation.

We could either reiterate through eval until we have enough items or use the existing loop (but that case is trickier to keep efficient while but using too much memory).

**Comment by pcuenca** [comment]
Should we do it externally using the checkpoints logged to wandb?

**Comment by borisdayma** [comment]
I think we can do it while training.

The reason we do it externally in dalle-mini is to avoid loading the VQGAN model and save some memory (not sure it's actually significant).

In this case it is already loaded and very fast to compute (should only take a few seconds).

**Comment by borisdayma** [comment]
This is done
